spring.application.name=middleware
# RabbitMQ Connection Settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# OpenFloat Custom Queue Settings
openfloat.rabbitmq.exchange=openfloat.erp.exchange
openfloat.rabbitmq.queue=erp.posting.queue
openfloat.rabbitmq.routing-key=payment.confirmed.key
# Safaricom Daraja API Settings (Sandbox Defaults)
safaricom.daraja.shortcode=174379
safaricom.daraja.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
safaricom.daraja.stk-push-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
safaricom.daraja.callback-url=https://openfloat.onrender.com/api/v1/callbacks/stk-push

# Embedded H2 datasource for local startup
spring.datasource.url=jdbc:h2:mem:middleware;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
safaricom.daraja.consumer-key=DJbzcHzQ4irgs1WkcdgQCAVQzQGhkg6Cu0h9rWmfG7sRm31r
safaricom.daraja.consumer-secret=qC4n93BpdaLL3fa3uHSYyqzQDqFe3nnVVCFY3WnxkYblf4z2lZrmb3hKHY1noW5B
safaricom.daraja.auth-url=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials