spring.application.name=middleware

# ==========================================
# RABBITMQ CONFIGURATION
# ==========================================
# Connects dynamically to CloudAMQP using your Render Environment Variable
spring.rabbitmq.addresses=${RABBITMQ_URL}

# Application Custom Queue Settings matching RabbitMQConfig.java
openfloat.rabbitmq.exchange=openfloat.erp.exchange
openfloat.rabbitmq.queue=openfloat.erp.queue
openfloat.rabbitmq.routing-key=erp.payment.success

# RabbitMQ Exponential Backoff & DLQ Policy
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.default-requeue-rejected=false


# ==========================================
# DATASOURCE & PERSISTENCE (POSTGRESQL)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect specifically for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# Disable H2 Console
spring.h2.console.enabled=false

# ==========================================
# SECURITY & ADMIN CREDENTIALS
# ==========================================
ADMIN_USERNAME=${ADMIN_USERNAME:default_admin}
ADMIN_PASSWORD=${ADMIN_PASSWORD:changeme123}

# ===================================
# SAFARICOM DARAJA API SETTINGS
# ===================================
safaricom.daraja.consumer-key=${DARAJA_CONSUMER_KEY}
safaricom.daraja.consumer-secret=${DARAJA_CONSUMER_SECRET}
safaricom.daraja.shortcode=${DARAJA_SHORTCODE:174379}
safaricom.daraja.passkey=${DARAJA_PASSKEY}
safaricom.daraja.stk-push-url=${DARAJA_STK_PUSH_URL:https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest}
safaricom.daraja.callback-url=${DARAJA_CALLBACK_URL:https://openfloat.onrender.com/api/v1/payments/callback}
safaricom.daraja.auth-url=${DARAJA_AUTH_URL:https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials}